<?php
/**
autoSound default Wishlist templates link.
@author Vladislav Romaniuk vlad96r@protonmial.com
@copyright 2020 Vlromaniuk
 */

/* @var \Magento\Wishlist\Block\Link $block */
?>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <img src="<?= $block->getViewFileUrl('images/whishlist.svg');  ?>" alt="wishlist">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().items.length" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
