<?php
/**
autoSound default Theme templates html topmenu.
@author Vladislav Romaniuk vlad96r@protonmial.com
@copyright 2020 Vlromaniuk
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <div class="nav">
        <div class="hover-menu">
            <p><?=__('All Categories')?></p>
            <img src="<?= $this->getViewFileUrl('images/topmenu.svg') ?>" alt="">
        </div>
        <ul class="ui-menu">
            <?= /* @noEscape */ $_menuHtml?>
            <?= $block->getChildHtml() ?>
        </ul>
    </div>
</nav>
