<?php
/**
autoSound default Catalog templates product compare link.
@author Vladislav Romaniuk vlad96r@protonmial.com
@copyright 2020 Vlromaniuk
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <img src="<?= $block->getViewFileUrl('images/compare.svg');  ?>" alt="compare">
    <a class="action compare" title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}">
        <?= $block->escapeHtml(__('Compare Products')) ?>
        <span class="counter qty" data-bind="text: compareProducts().count"></span>
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
