<?php
/**
 *autoSTore default Catalog templates product view gallery.
 *@author Vladislav Romaniuk vlad96r@protonmial.com
 *@copyright 2020 Vlromaniuk
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "thumbs",
                    "loop": true,
                    "keyboard": true,
                    "arrows": false,
                    "allowfullscreen": false,
                    "showCaption": false,
                    "maxwidth": 400,
                    "maxheight": 400,
                    "thumbwidth": 72,
                    "thumbheight": 68,
                    "transitionduration": 500,
                    "transition": "crossfade",
                    "navarrows": false,
                    "navtype": "thumbs",
                    "navdir": "vertical",
                    "thumbmargin":77
                },
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
